name: Build and Dockerize Spring Boot App

on:
  push:
    branches:
      - ops

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java and Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Verify the existence of the JAR file
      - name: Verify JAR file exists
        run: |
          # Check if the JAR file exists in the target directory
          if [ ! -f target/*.jar ]; then
            echo "JAR file not found in target directory. Exiting."
            exit 1
          fi
          echo "JAR file found: $(ls target/lorabackend-*.jar)"
      
      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t seifmsd464325/lorabackend:latest .

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push seifmsd464325/lorabackend:latest
