name: Build and Dockerize Spring Boot App

on:
  push:
    branches:
      - ops 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java and Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the Spring Boot application
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Verify the existence of the .jar file
      - name: Verify JAR File Existence
        run: |
          if [ ! -f target/lorabackend-*.jar ]; then
            echo "JAR file not found. Build might have failed!"
            exit 1
          fi
          echo "JAR file exists. Proceeding to Docker build."

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t seifmsd464325/lorabackend:latest .
          docker push seifmsd464325/lorabackend:latest
